---
apiVersion: v1
kind: Service
metadata:
  name: haproxy-service
  namespace: haproxy
spec:
  selector:
    app: haproxy
  ports:
  - name: app
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: metrics
    protocol: TCP
    port: 8404   # <-- Expose Prometheus metrics
    targetPort: 8404
  type: LoadBalancer