apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: haproxy-hpa
  namespace: haproxy
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: haproxy
  minReplicas: 2
  maxReplicas: 50
  metrics:
  - type: External
    external:
      metric:
        name: haproxy_http_requests_per_second
      target:
        type: AverageValue
        averageValue: 2000