server:
  extraScrapeConfigs: |
    scrape_configs:
      - job_name: 'haproxy'
        static_configs:
          - targets: ['haproxy-service.haproxy.svc.cluster.local:8404']

      - job_name: 'nginx'
        static_configs:
          - targets: ['nginx-service.nginx.svc.cluster.local:9113']

      - job_name: 'backend'
        static_configs:
          - targets: ['backend-service.app.svc.cluster.local:5001']
